### ISSUE TITLE
adding metadata to published texts

### ISSUE THREAD

**Issue by matthewrutz** [oracc/queries#1]
Is there documentation on how to add metadata to the left-hand pane in the published Oracc text environment?

Looking at other Oracc projects I would like to be able to add things like the following:

- sortable place/genre/period tagging akin to CAMS
- details (provenance details, script, etc.) NOT pulled from CDLI which is often incomplete or even wrong
- bibliography
- sources (e.g., DCCLT)
- related text (also akin to DCCLT)

- export options (e.g., TEI, etc.); not strictly metadata but still useful to add (akin to ADsD)

Many thanks!

**Comment by EleanorRobson** [comment]
Matthew, sorry I missed this before. The short answer is that you need to build a custom catalogue for your project, details here: http://oracc.museum.upenn.edu/doc/help/managingprojects/catalogues/index.html
